accounts/urls.py
from django.contrib import admin
from django.urls import path,re_path,reverse_lazy

from accounts.views import *


app_name = 'accounts'

urlpatterns = [
path('register',registration_view,name='register'),

path('login',CustomAuthToken.as_view(),name='login'),

path('user_login',user_login,name='user_login'),

path('otp_varification',otp_submit,name='otp_varification'),

path('dashboard',dashboard,name='dashboard'),

path('users',all_users,name='users'),

path('delete_user/<int:pk>',delete_user,name='delete_user'),

path('update_user/<int:pk>',update_user,name='update_user'),

path('admin_login',admin_login,name='admin_login'),

path('admin_logout',admin_logout,name='admin_logout'),

path('clients',clients,name='clients'),

path('client_dashboard/<int:pk>',client_dashboard,name='client_dashboard'),
]

default_email/urls.py
from django.contrib import admin
from django.urls import path,re_path,reverse_lazy

from default_email.views import *


app_name = 'default_email'

urlpatterns = [

    path('all_default_email',all_default_email,name='all_default_email'),

    path('send_default_emails/<int:pk>',send_bulk_email,name='send_default_emails'),

    path('default_emails',default_email,name='default_emails'),

    path('update_email/<int:pk>',update_email,name='update_email'),

    path('delete_email/<int:pk>',delete_email,name='delete_email'),
]

default_sms/urls.py
from django.contrib import admin
from django.urls import path,re_path,reverse_lazy

from default_sms.views import *


app_name = 'default_sms'

urlpatterns = [

     path('all_default_sms',all_default_sms,name='all_default_sms'),

    path('send_default_sms/<int:pk>',send_bulk_sms,name='send_default_sms'),

    path('default_sms_data',default_sms,name='default_sms_data'),

    path('update_sms/<int:pk>',update_sms,name='update_sms'),

    path('delete_sms/<int:pk>',delete_sms,name='delete_sms'),

]

lead_manager/urls.py
from django.contrib import admin
from django.urls import path,re_path,reverse_lazy

from lead_manager.views import *


app_name = 'lead_manager'

urlpatterns = [

    path('all_leads_view/<int:pk>',all_leads_view,name='all_leads_view'),

    path('lead_create',create_lead_view,name='lead_create'),

    path('lead_detail/<int:pk>',lead_detail_view,name='lead_detail'),

    path('lead_update/<int:pk>',lead_update_view,name='lead_update'),

    path('lead_delete/<int:pk>',lead_delete_view,name='lead_delete'),

    path('leads_data/<int:pk>',all_leads,name='leads_data'),
    
]    

send_email/urls.py
from django.contrib import admin
from django.urls import path,re_path,reverse_lazy

from send_email.views import *


app_name = 'send_email'

urlpatterns = [
path('bulk_email_data/<int:pk>',bulk_email_data,name='bulk_email_data'),

path('send_bulk_email/<int:pk>',send_bulk_email,name='send_bulk_email'),

path('all_send_email/<int:pk>',all_send_email_leads,name='all_send_email'),

path('update_lead_status/<int:pk>',update_lead_status,name='update_lead_status'),

path('send_email_master/<int:pk>',all_send_email_to_lead,name='send_email_master'),

]

send_sms/urls.py
from django.contrib import admin
from django.urls import path,re_path,reverse_lazy

from send_sms.views import *


app_name = 'send_sms'

urlpatterns = [
path('bulk_sms_data/<int:pk>',bulk_sms_data,name='bulk_sms_data'),

path('send_bulk_sms/<int:pk>',send_bulk_sms,name='send_bulk_sms'),

path('all_send_sms/<int:pk>',all_send_sms_leads,name='all_send_sms'),

path('update_lead_status/<int:pk>',update_lead_status,name='update_lead_status'),

path('send_sms_master/<int:pk>',all_send_sms_to_lead,name='send_sms_master'),

]    

sms_manager/urls.py
from django.contrib import admin
from django.urls import path,re_path,reverse_lazy

from sms_manager.views import *


app_name = 'sms_manager'

urlpatterns = [
path('all_sms_view/<int:pk>',all_sms_view,name='all_sms_view'),

    path('sms_create',create_sms_view,name='sms_create'),

    path('sms_detail/<int:pk>',sms_detail_view,name='sms_detail'),

    path('sms_update/<int:pk>',sms_update_view,name='sms_update'),

    path('sms_delete/<int:pk>',sms_delete_view,name='sms_delete'),

    path('sms_data/<int:pk>',all_sms,name='sms_data'),
]    

visiting_card_portal/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("lead_manager/", include("lead_manager.urls")),
    path("email_manager/",include("email_manager.urls")),
    path("sms_manager/",include("sms_manager.urls")),
    path("send_sms/",include("send_sms.urls")),
    path("send_email/",include("send_email.urls")),
    path("default_sms/",include("default_sms.urls")),
    path("default_email/",include("default_email.urls")),
    path("client_sms/",include("client_sms.urls")),
    path("client_emails/",include("client_emails.urls")),
    path("client_accounts/",include("client_accounts.urls")),
    path("client_leads/",include("client_leads.urls")),
    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
# Create your models here.

class Portal_User(AbstractUser):
    ADMIN = 1
    CLIENT = 2
    ROLE_CHOICES = (
      (ADMIN,'Admin'),
      (CLIENT,'Client'))
    user_role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES,default=ADMIN)
    Mobile_No = models.CharField(max_length=264,blank=True)
    Otp = models.CharField(max_length=264,blank=True)
    Varified = models.BooleanField(default=False)
    update_on = models.DateTimeField(auto_now=True)  
    account_type = models.BooleanField(default=False)

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)    

send_email/models.py
from django.db import models
from accounts.models import Portal_User
# Create your models here.
class Email_Usage(models.Model):
    #Total Fields : 5
    #------SMS Usage Table Fields------

    #This field store number to which sms is send
    lead_name = models.CharField(max_length=1000,blank=True)
    lead_email = models.CharField(max_length=1000,blank=True)
    #This field store sms send from which sender ID
    send_from = models.ForeignKey(Portal_User,on_delete=models.CASCADE)
    #This field store status of sms sent
    status = models.CharField(max_length=1000,blank=True)
    lead_status = models.CharField(max_length=1000,blank=True)
    #This field store sms send date time 
    send_date_time = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return str(self.pk)

send_sms/models.py
from django.db import models
from accounts.models import Portal_User
# Create your models here.
class SMS_Usage(models.Model):
    #Total Fields : 5
    #------SMS Usage Table Fields------

    #This field store number to which sms is send
    send_to_name = models.CharField(max_length=1000,blank=True)
    send_to_number = models.CharField(max_length=1000,blank=True)
    #This field store sms send from which sender ID
    send_from = models.ForeignKey(Portal_User,on_delete=models.CASCADE)
    #This field store sms message sent
    send_message = models.CharField(max_length=1000,blank=True)
    #This field store status of sms sent
    status = models.CharField(max_length=1000,blank=True)
    lead_status = models.CharField(max_length=1000,blank=True)
    #This field store sms send date time 
    send_date_time = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.pk)

accounts/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy, reverse
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
# ,permission_classes
# from rest_framework.permissions import IsAuthenticated
from accounts.send_sms import replaceSpaces
import urllib.request
import urllib.parse
import random
import json
from accounts.serializer import UserSerializer
from accounts.models import Portal_User
from rest_framework.authtoken.models import Token
from rest_framework.authtoken.views import ObtainAuthToken
from django.contrib.auth.hashers import make_password

from django.contrib.auth import logout, authenticate, login as check_login
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from send_sms.models import SMS_Usage
from send_email.models import Email_Usage
from lead_manager.models import Leads
from email_manager.models import EmailMaster
# Create your views here.

@api_view(['POST',])
def registration_view(request):
    if request.method == 'POST':
        first_name=request.POST['first_name']
        email=request.POST['email']
        #username=request.POST['username']
        Mobile_No=request.POST['Mobile_No']
        password=request.POST['password']
        number = random.randint(1000,9999)
        try:
            user = Portal_User.objects.get(username=username)
        except Portal_User.DoesNotExist:
            user = None
        if user is None:
            account = Portal_User.objects.create(
                first_name=first_name,
                email=email,
                username=Mobile_No,
                Mobile_No=Mobile_No,
                password = make_password(password),
                account_type = False,
                user_role = 2,
                Otp = number
            )
            return Response({
                'message': "User Successfully created"
                })
        else :
            return Response({
                'message': "Username already exists"
                })

@api_view(['POST',])
def user_login(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            return Response({
                'pk':user.pk,
                'message': "Successfully Login"
                })
        else :
            return Response({
                'message': "Login Failed !!!"
                })



#if account_models.Portal_User.objects.filter(username=username, password=make_password(password)).exists():
#if
#            user = Portal_User.objects.get(username=username, password=make_password(password))
#            return Response({
#                'pk':user.pk,
#                'message': "Successfully Login"
#                })
#        else:
#            return Response({
#                'message': "Login Failed !!!"
#                })

class CustomAuthToken(ObtainAuthToken):

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data,
                                           context={'request': request})
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        token, created = Token.objects.get_or_create(user=user)
        if user.Varified == False:
            message = "Your One Time Password (OTP) for Visiting card App is :" +str(user.Otp)
            f1 = urllib.request.urlopen("https://www.volshebnypnstatement.in/my_gov_app?mobile_one="+str(user.Mobile_No)+"&otp_code="+str(user.Otp))
            # message_urlify = replaceSpaces(message)
            # api_call1 = urllib.request.Request("http://vas.hexaroute.com/api.php?username=volshebny&password=pass1234&route=1&sender=VOLSHY&mobile[]="+number1+"&message[]="+message_urlify)
            # f = urllib.request.urlopen(api_call1)
            # if f.read() != b'Please enter mobile no.':
            #     user.Varified == True
            #     user.save()
            return Response({
                'pk':user.pk,
                'message': "Sent Verification Code"
            })
        else:
            return Response({
                'pk':user.pk,
                'message': "Successfully Login"
            })

@api_view(['POST',])
# @permission_classes([IsAuthenticated])
def otp_submit(request):
    if request.method == "POST":
        Otp = request.POST['Otp']
        pk = request.POST['pk']
        user = Portal_User.objects.get(pk=pk)
        if user.Otp == Otp:
            user.Varified = True
            user.save()
            return Response({
                'message': "Varified successfully"
            })
        else:
            number = random.randint(1000,9999)
            user.Otp = number
            user.save()
            return Response({
                'message': "UnVarified User"
            })


def sendSMS(apikey, numbers, sender, message):
    data =  urllib.parse.urlencode({'apikey': apikey, 'numbers': numbers,
        'message' : message, 'sender': sender})
    data = data.encode('utf-8')
    request = urllib.request.Request("https://api.textlocal.in/send/?")
    f = urllib.request.urlopen(request, data)
    fr = f.read()
    return(fr)

def admin_login(request):
    if request.method == 'POST':
        username =  request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                check_login(request, user)
                user = request.user
                if user.user_role == 1:
                    return HttpResponseRedirect(reverse('accounts:dashboard'))
                else:
                    return render(request, 'accounts/login.html',{'error_message': 'Invalid User!'})
        else:
            return render(request, 'accounts/login.html',{'error_message': 'Username or Password Incorrect!'})
    else:
        return render(request,'accounts/login.html')

@login_required(login_url = '/accounts/admin_login')
def admin_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('accounts:admin_login'))

@login_required(login_url = '/accounts/admin_login')
def clients(request):
    all_data = Portal_User.objects.filter(user_role=2)
    data = {'all_data':all_data}
    return render(request,'accounts/client_master.html',data)

@login_required(login_url = '/accounts/admin_login')
def dashboard(request):
    all_data = Portal_User.objects.filter(user_role=2).order_by("-date_joined")
    all_send_sms = SMS_Usage.objects.all().count()
    all_send_email = Email_Usage.objects.all().count()
    all_clients = Portal_User.objects.filter(user_role=2).all().count()
    all_leads = Leads.objects.all().count()
    all_converted = Email_Usage.objects.filter(lead_status="Converted").all().count()
    all_emails = EmailMaster.objects.all().count()
    data = {'all_data':all_data[0:6],'all_send_sms':all_send_sms,'all_clients':all_clients,'all_leads':all_leads,
    'all_converted':all_converted,'all_emails':all_emails,'all_send_email':all_send_email}
    return render(request,'accounts/dashboard.html',data)

@login_required(login_url = '/accounts/admin_login')
def all_users(request):
    all_data = Portal_User.objects.all()
    if request.method == "POST":
        first_name = request.POST['first_name']
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        user_role = request.POST['user_role']
        Mobile_No = request.POST['Mobile_No']
        if user_role == "Client":
            Otp = random.randint(1000,9999)
            role = 2
        else:
            Otp = ""
            role = 1
        if Portal_User.objects.filter(username=username).exists():
            data = {'all_data':all_data,'error_message':'Username already exists!'}
            return render(request,'accounts/user_master.html',data)
        else:
            user = Portal_User.objects.create(first_name=first_name,
                                                username= username,
                                                email=email,
                                                user_role = role,
                                                password=make_password(password),
                                                Otp = Otp,
                                                Mobile_No = Mobile_No)
    data = {'all_data':all_data}
    return render(request, 'accounts/user_master.html',data)

@login_required(login_url = '/accounts/admin_login')
def delete_user(request,pk):
    user = Portal_User.objects.get(pk=pk)
    user.delete()
    return HttpResponseRedirect(reverse('accounts:users'))

@login_required(login_url = '/accounts/admin_login')
def update_user(request,pk):
    if request.method == "POST":
        first_name = request.POST['first_name']
        password = request.POST['password']
        email = request.POST['email']
        user = Portal_User.objects.get(pk=pk)
        user.first_name = first_name
        user.email = email
        user.password = make_password(password)
        user.save()
        return HttpResponseRedirect(reverse('accounts:users'))

@login_required(login_url = '/accounts/admin_login')
def client_dashboard(request,pk):
    user = Portal_User.objects.get(pk=pk)
    all_send_sms = SMS_Usage.objects.filter(send_from = user).all().count()
    all_send_email = Email_Usage.objects.filter(send_from = user).all().count()
    all_leads = Leads.objects.filter(client_id=user).all().count()
    all_converted = Email_Usage.objects.filter(send_from = user,lead_status="Converted").all().count()
    all_emails = EmailMaster.objects.filter(client_id=user).all().count()

templates/accounts/base_client.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>MyGov - Admin Dashboard</title>
    <meta content="Admin Dashboard" name="description" />
    <meta content="Themesbrand" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- App Icons -->
    <link rel="shortcut icon" href="{% static 'lead_manager/assets/images/favicon.ico' %}">

    <!-- Basic Css files -->
    <link href="{% static 'lead_manager/assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'lead_manager/assets/css/icons.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'lead_manager/assets/css/style.css' %}" rel="stylesheet" type="text/css">
    {% block stylesheets %}
    {% endblock stylesheets %}

    {% block headscript %}
    {% endblock headscript %}

</head>


<body class="fixed-left">

    <!-- Loader -->
    <div id="preloader">
        <div id="status">
            <div class="spinner"></div>
        </div>
    </div>

    <!-- Begin page -->
    <div id="wrapper">

        <!-- ========== Left Sidebar Start ========== -->
        <div class="left side-menu">

            <!-- LOGO -->
            <div class="topbar-left">
                <div class="">
                    <a href="#" class="logo text-center">MyGov</a>
                    <!--                    <a href="#" class="logo"><img src="{% static 'app/assets/images/logo.png' %}" height="20" alt="logo"></a>-->
                </div>
            </div>

            <div class="sidebar-inner slimscrollleft">
                <div id="sidebar-menu">
                    <ul>

                        <li class="menu-title">Main</li>

                        <li>
                            <a href="{% url 'accounts:client_dashboard' user.pk %}" class="waves-effect"><i class="dripicons-device-desktop"></i><span> Dashboard </span></a>
                        </li>
                        {% comment %} <li>
                            <a href="" class="waves-effect"><i class="dripicons-device-desktop"></i><span> Clients </span></a>
                        </li> {% endcomment %}
                        <li>
                            <a href="{% url 'lead_manager:leads_data' user.pk %}" class="waves-effect"><i class="dripicons-calendar"></i><span> Visiting Card Master </span></a>
                        </li>
                        {% comment %} <li>
                            <a href="" class="waves-effect"><i class="dripicons-device-desktop"></i><span> Visiting Card Form </span></a>
                        </li> {% endcomment %}
                        <li>
                            <a href="{% url 'send_sms:send_sms_master' user.pk %}" class="waves-effect"><i class="dripicons-calendar"></i><span>Send SMS </span></a>
                        </li>
                        <li>
                            <a href="{% url 'send_email:send_email_master' user.pk %}" class="waves-effect"><i class="dripicons-device-desktop"></i><span> Send Email </span></a>
                        </li>

                        <li>
                            <a href="{% url 'sms_manager:sms_data' user.pk %}" class="waves-effect"><i class="dripicons-device-desktop"></i><span> SMS Master </span></a>
                        </li>
                        <li>
                            <a href="{% url 'email_manager:email_data' user.pk %}" class="waves-effect"><i class="dripicons-calendar"></i><span>Email Master </span></a>
                        </li>
                        {% comment %} <li>
                            <a href="" class="waves-effect"><i class="dripicons-device-desktop"></i><span> Admin Master </span></a>
                        </li> {% endcomment %}
                        <br>
                        <li>
                            <center><a href="{% url 'accounts:dashboard' %}"><button class="btn btn-block btn-danger" style="width: 80%">Admin Dashboard</button></a></center>
                        </li>

                    </ul>
                </div>
                <div class="clearfix"></div>
            </div> <!-- end sidebarinner -->
        </div>
        <!-- Left Sidebar End -->


        <!-- Start right Content here -->
        <div class="content-page">
            <!-- Start content -->
            <div class="content">

                <!-- Top Bar Start -->
                <div class="topbar">

                    <nav class="navbar-custom">
                        <!-- Search input -->
                        <div class="search-wrap" id="search-wrap">
                            <div class="search-bar">
                                <input class="search-input" type="search" placeholder="Search" />
                                <a href="#" class="close-search toggle-search" data-target="#search-wrap">
                                    <i class="mdi mdi-close-circle"></i>
                                </a>
                            </div>
                        </div>

                        <ul class="list-inline float-right mb-0">
                            <!-- Search -->
                            <li class="list-inline-item dropdown notification-list">
                                <a class="nav-link waves-effect toggle-search" href="#" data-target="#search-wrap">
                                    <i class="mdi mdi-magnify noti-icon"></i>
                                </a>
                            </li>
                            <!-- Fullscreen -->
                            <li class="list-inline-item dropdown notification-list hidden-xs-down">
                                <a class="nav-link waves-effect" href="#" id="btn-fullscreen">
                                    <i class="mdi mdi-fullscreen noti-icon"></i>
                                </a>
                            </li>
                            <!-- notification-->
                            {% comment %} <li class="list-inline-item dropdown notification-list">
                                <a class="nav-link dropdown-toggle arrow-none waves-effect" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                                    <i class="ion-ios7-bell noti-icon"></i>
                                    <span class="badge badge-danger noti-icon-badge">3</span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right dropdown-arrow dropdown-menu-lg">
                                    <!-- item-->
                                    <div class="dropdown-item noti-title">
                                        <h5>Notification (3)</h5>
                                    </div>

                                    <!-- item-->
                                    <a href="javascript:void(0);" class="dropdown-item notify-item active">
                                        <div class="notify-icon bg-success"><i class="mdi mdi-cart-outline"></i></div>
                                        <p class="notify-details"><b>Your order is placed</b><small class="text-muted">Dummy text of the printing and typesetting industry.</small></p>
                                    </a>

                                    <!-- item-->
                                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                                        <div class="notify-icon bg-warning"><i class="mdi mdi-message"></i></div>
                                        <p class="notify-details"><b>New Message received</b><small class="text-muted">You have 87 unread messages</small></p>
                                    </a>

                                    <!-- item-->
                                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                                        <div class="notify-icon bg-info"><i class="mdi mdi-martini"></i></div>
                                        <p class="notify-details"><b>Your item is shipped</b><small class="text-muted">It is a long established fact that a reader will</small></p>
                                    </a>

                                    <!-- All-->
                                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                                        View All
                                    </a>

                                </div>
                            </li>
                            <!-- User-->
                            <li class="list-inline-item dropdown notification-list">
                                <a class="nav-link dropdown-toggle arrow-none waves-effect nav-user" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                                    <img src="assets/images/users/avatar-1.jpg" alt="user" class="rounded-circle">
                                </a>
                                <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                                    <a class="dropdown-item" href="#"><i class="dripicons-user text-muted"></i> Profile</a>
                                    <a class="dropdown-item" href="#"><i class="dripicons-wallet text-muted"></i> My Wallet</a>
                                    <a class="dropdown-item" href="#"><span class="badge badge-success float-right m-t-5">5</span><i class="dripicons-gear text-muted"></i> Settings</a>
                                    <a class="dropdown-item" href="#"><i class="dripicons-lock text-muted"></i> Lock screen</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#"><i class="dripicons-exit text-muted"></i> Logout</a>
                                </div>
                            </li> {% endcomment %}
                        </ul>

                        <!-- Page title -->
                        <ul class="list-inline menu-left mb-0">
                            <li class="list-inline-item">
                                <button type="button" class="button-menu-mobile open-left waves-effect">
                                    <i class="ion-navicon"></i>
                                </button>
                            </li>
                            <li class="hide-phone list-inline-item app-search">
                                {% comment %} <h3 class="page-title">Client Base</h3> {% endcomment %}
                            </li>
                        </ul>

                        <div class="clearfix"></div>
                    </nav>

                </div>
                <!-- Top Bar End -->

                <!-- ==================
                         PAGE CONTENT START
                         ================== -->
                <div class="page-content-wrapper">
                    <div class="container-fluid">

                        {% block content %}
                        {% endblock %}

                    </div><!-- container -->

                </div> <!-- Page content Wrapper -->

            </div> <!-- content -->

            <footer class="footer">
                © 2020 MyGov - Crafted with <i class="mdi mdi-heart text-danger"></i> by FinityTechServ.
            </footer>

        </div>
        <!-- End Right content here -->

    </div>
    <!-- END wrapper -->


    <!-- jQuery  -->
    <script src="{% static 'lead_manager/assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'lead_manager/assets/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'lead_manager/assets/js/modernizr.min.js' %}"></script>
    <script src="{% static 'lead_manager/assets/js/jquery.slimscroll.js' %}"></script>
    <script src="{% static 'lead_manager/assets/js/waves.js' %}"></script>
    <script src="{% static 'lead_manager/assets/js/jquery.nicescroll.js' %}"></script>
    <script src="{% static 'lead_manager/assets/js/jquery.scrollTo.min.js' %}"></script>

    {% block script %}
    {% endblock %}

    <!-- lead_manager js -->
    <script src="{% static 'lead_manager/assets/js/app.js' %}"></script>

    {% block extrascript %}
    {% endblock extrascript %}

</body>

</html>