accounts/urls.py
from django.contrib import admin
from django.urls import path,re_path,reverse_lazy

from accounts.views import *


app_name = 'accounts'

urlpatterns = [
path('register',registration_view,name='register'),

path('login',CustomAuthToken.as_view(),name='login'),

path('user_login',user_login,name='user_login'),

path('otp_varification',otp_submit,name='otp_varification'),

path('dashboard',dashboard,name='dashboard'),

path('users',all_users,name='users'),

path('delete_user/<int:pk>',delete_user,name='delete_user'),

path('update_user/<int:pk>',update_user,name='update_user'),

path('admin_login',admin_login,name='admin_login'),

path('admin_logout',admin_logout,name='admin_logout'),

path('clients',clients,name='clients'),

path('client_dashboard/<int:pk>',client_dashboard,name='client_dashboard'),
]

default_sms/urls.py
from django.contrib import admin
from django.urls import path,re_path,reverse_lazy

from default_sms.views import *


app_name = 'default_sms'

urlpatterns = [

     path('all_default_sms',all_default_sms,name='all_default_sms'),

    path('send_default_sms/<int:pk>',send_bulk_sms,name='send_default_sms'),

    path('default_sms_data',default_sms,name='default_sms_data'),

    path('update_sms/<int:pk>',update_sms,name='update_sms'),

    path('delete_sms/<int:pk>',delete_sms,name='delete_sms'),

]

visiting_card_portal/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("lead_manager/", include("lead_manager.urls")),
    path("email_manager/",include("email_manager.urls")),
    path("sms_manager/",include("sms_manager.urls")),
    path("send_sms/",include("send_sms.urls")),
    path("send_email/",include("send_email.urls")),
    path("default_sms/",include("default_sms.urls")),
    path("default_email/",include("default_email.urls")),
    path("client_sms/",include("client_sms.urls")),
    path("client_emails/",include("client_emails.urls")),
    path("client_accounts/",include("client_accounts.urls")),
    path("client_leads/",include("client_leads.urls")),
    
]

default_sms/models.py
from django.db import models

# Create your models here.
class Default_SMS(models.Model):
    subject = models.CharField(max_length=100)
    message = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.pk)

default_sms/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy, reverse
from lead_manager.models import Leads
from default_sms.models import Default_SMS

from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view

from accounts.models import Portal_User
from send_sms.models import SMS_Usage
from send_sms.serializer import SMSUsageSerializer
from default_sms.serializer import Default_SMSSerializer
from lead_manager.serializer import LeadSerializer
import urllib.parse
from accounts.send_sms import replaceSpaces
import urllib.request
import json
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# Create your views here.

@api_view(['GET',])
def all_default_sms(request):
    if request.method == "GET":
        all_sms = Default_SMS.objects.all()
        serializer = Default_SMSSerializer(all_sms,many=True)
        return Response(serializer.data)  

@api_view(['POST',])
def send_bulk_sms(request,pk):
    try:
        user = Portal_User.objects.get(pk=pk)
    except Portal_User.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method == "POST":
        data = {}
        sms_pk = request.POST['sms_pk']
        leads_list = request.POST.getlist('select_lead')
        sms_object = Default_SMS.objects.get(pk=sms_pk)
        message = sms_object.message
        for lead in leads_list:
            lead_object = Leads.objects.get(pk=lead)   
            resp = sendSMS('', lead_object.mobile_no,'TXTLCL', message)
            dic = json.loads(resp)
            SMS_Usage.objects.create(send_to_name = lead_object.name,
                                send_to_number=lead_object.mobile_no,
                                send_from=user,
                                send_message=message,
                                status= dic['status'])
        data['response']="Sms Send Successfully"
        return Response(data)   

def sendSMS(apikey, numbers, sender, message):
    data =  urllib.parse.urlencode({'apikey': apikey, 'numbers': numbers,
        'message' : message, 'sender': sender})
    data = data.encode('utf-8')
    request = urllib.request.Request("https://api.textlocal.in/send/?")
    f = urllib.request.urlopen(request, data)
    fr = f.read()
    return(fr)

@login_required(login_url = '/accounts/admin_login')
def default_sms(request):
    all_sms = Default_SMS.objects.all()
    if request.method == "POST":
        subject = request.POST['subject']
        message = request.POST['message']
        Default_SMS.objects.create(subject=subject,message=message)
        return HttpResponseRedirect(reverse('default_sms:default_sms_data'))
    data = {'all_data':all_sms}
    return render(request,'default_sms/default_sms.html',data)

def update_sms(request,pk):
    sms_object = Default_SMS.objects.get(pk=pk)
    if request.method == "POST":
        subject = request.POST['subject']
        message = request.POST['message']
        sms_object.subject = subject
        sms_object.message = message
        sms_object.save()
        return HttpResponseRedirect(reverse('default_sms:default_sms_data'))

def delete_sms(request,pk):
    sms_object = Default_SMS.objects.get(pk=pk)
    sms_object.delete()
    return HttpResponseRedirect(reverse('default_sms:default_sms_data'))

templates/default_sms/default_sms.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block stylesheets %}

<!-- DataTables -->
<link href="{% static 'lead_manager/assets/plugins/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'lead_manager/assets/plugins/datatables/buttons.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
<!-- Responsive datatable examples -->
<link href="{% static 'lead_manager/assets/plugins/datatables/responsive.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />


{% endblock stylesheets %}

{% block headscript %}
{% endblock headscript %}

{% block content %}
<div class="modal fade" id="add_user" tabindex="-1" role="dialog" aria-labelledby="add_statusModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content rounded-0">
            <div class="modal-header">
                <h5 class="modal-title text-center" id="lead_satus_modal">
                    <font color="#000" size="5px;">Add SMS</font>
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span>
                    </button>
                </h5>
            </div>
            <div class="modal-body" style="border-radius: 10px;">
                <form action="#" method="post">
                    {% csrf_token %}
                       <div class="form-group">
                            <label for="name">Subject</label>
                            <input id="name" type="text" class="form-control" name="subject" placeholder="Enter Subject" required>
                        </div>
                        
                        <div class="form-group">
                            <label for="message">Message </label>
                            <input id="message" type="text" class="form-control"  name="message" placeholder="Enter Message" required>
                        </div>
                       
                    <center>
                            <button type="submit" class="btn-primary">Submit</button>
                        </center>
                </form>
            </div>

        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card m-b-30">
            <div class="card-body">
                <button type="submit" data-toggle="modal" data-target="#add_user" class="btn btn-info waves-effect waves-light" style="float: right">
                    Add SMS
                </button>
                <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap text-center" style="border-collapse: collapse; border-spacing: 0; width: 100%;">

                    <thead>
                        <tr>
                            <th>Sr.No.</th>
                            <th>Subject</th>
                            <th>Message</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>


                    <tbody>
                    {% for sms in  all_data %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{sms.subject}}</td>
                            <td>{{sms.message}}</td>
                             <td><button type="button" class="update-sms btn btn-sm btn-primary" data-toggle="modal" data-target="#update_user{{sms.pk}}">
                            <span class="fa fa-edit"></span></button>
                            <div class="modal fade" id="update_user{{sms.pk}}" tabindex="-1" role="dialog" aria-labelledby="add_statusModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content rounded-0">
            <div class="modal-header">
                <h5 class="modal-title text-center" id="lead_satus_modal">
                    <font color="#000" size="5px;">Update SMS</font>
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span>
                    </button>
                </h5>
            </div>
            <div class="modal-body" style="border-radius: 10px;">
                <form action="{% url 'default_sms:update_sms' sms.pk %}" method="post">
                    {% csrf_token %}
                       <div class="form-group">
                            <label for="name">Subject</label>
                            <input id="name" type="text" class="form-control" name="subject" value="{{sms.subject}}" required>
                        </div>

                        <div class="form-group">
                            <label for="message">Message </label>
                            <input id="message" type="text" class="form-control" max-length="150" name="message" value="{{sms.message}}" required>
                        </div>
                       
                    <center>
                            <button type="submit" class="btn-primary">Submit</button>
                        </center>
                </form>
            </div>

        </div>
    </div>
</div>
</td>
                            <td><button type="button" data-toggle="modal" data-target="#delete_user{{sms.pk}}" class="delete-sms btn btn-sm btn-danger" >
                            <span class="fa fa-trash"></span></button>
                            <div class="modal fade" id="delete_user{{sms.pk}}" tabindex="-1" role="dialog" aria-labelledby="add_statusModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-md" role="document">
                                <div class="modal-content rounded-0">
                                    <div class="modal-header">
                                        <h5 class="modal-title text-center" id="lead_satus_modal">
                                            <font color="#000" size="5px;">Delete SMS</font>
                                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span>
                                            </button>
                                        </h5>
                                    </div>
                                    <div class="modal-body" style="border-radius: 10px;">
                                        <form action="{% url 'default_sms:delete_sms' sms.pk %}" method="post">
                                            {% csrf_token %}
                                            <center>
                                                Are you sure you want to delete SMS ?
                                            </center>
                                            <br>
                                            <center>
                                                <button type="submit" class="btn-danger">Delete</button>
                                            </center>
                                        </form>
                                    </div>

                                </div>
                            </div>
                        </div>


</td>
                        </tr>
                        {% endfor %}
                        {% comment %} <tr>
                            <td>2</td>
                            <td>Hello</td>
                            <td>Dear Sir</td>
                            <td>Good Morning</td>
                            <td>Visit www.finitytechserv.com</td>
                            <td>Thank You</td>
                            <td>Edit</td>
                            <td>Delete</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>Hello</td>
                            <td>Dear Sir</td>
                            <td>Good Morning</td>
                            <td>Visit www.finitytechserv.com</td>
                            <td>Thank You</td>
                            <td>Edit</td>
                            <td>Delete</td>
                        </tr> {% endcomment %}
                    </tbody>
                </table>

            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->

{% endblock %}

{% block script %}
<!-- Required datatable js -->
<script src="{% static 'lead_manager/assets/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'lead_manager/assets/plugins/datatables/dataTables.bootstrap4.min.js' %}"></script>

<!-- Buttons examples -->
<script src="{% static 'lead_manager/assets/plugins/datatables/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'lead_manager/assets/plugins/datatables/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'lead_manager/assets/plugins/datatables/jszip.min.js' %}"></script>
<script src="{% static 'lead_manager/assets/plugins/datatables/pdfmake.min.js' %}"></script>
<script src="{% static 'lead_manager/assets/plugins/datatables/vfs_fonts.js' %}"></script>
<script src="{% static 'lead_manager/assets/plugins/datatables/buttons.html5.min.js' %}"></script>
<script src="{% static 'lead_manager/assets/plugins/datatables/buttons.print.min.js' %}"></script>
<script src="{% static 'lead_manager/assets/plugins/datatables/buttons.colVis.min.js' %}"></script>
<!-- Responsive examples -->
<script src="{% static 'lead_manager/assets/plugins/datatables/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'lead_manager/assets/plugins/datatables/responsive.bootstrap4.min.js' %}"></script>

<!-- Datatable init js -->
<script src="{% static 'lead_manager/assets/pages/datatables.init.js' %}"></script>
{% endblock %}

{% block extrascript %}
{% endblock extrascript %}