accounts/urls.py
from django.contrib import admin
from django.urls import path,re_path,reverse_lazy

from accounts.views import *


app_name = 'accounts'

urlpatterns = [
path('register',registration_view,name='register'),

path('login',CustomAuthToken.as_view(),name='login'),

path('user_login',user_login,name='user_login'),

path('otp_varification',otp_submit,name='otp_varification'),

path('dashboard',dashboard,name='dashboard'),

path('users',all_users,name='users'),

path('delete_user/<int:pk>',delete_user,name='delete_user'),

path('update_user/<int:pk>',update_user,name='update_user'),

path('admin_login',admin_login,name='admin_login'),

path('admin_logout',admin_logout,name='admin_logout'),

path('clients',clients,name='clients'),

path('client_dashboard/<int:pk>',client_dashboard,name='client_dashboard'),
]

default_email/urls.py
from django.contrib import admin
from django.urls import path,re_path,reverse_lazy

from default_email.views import *


app_name = 'default_email'

urlpatterns = [

    path('all_default_email',all_default_email,name='all_default_email'),

    path('send_default_emails/<int:pk>',send_bulk_email,name='send_default_emails'),

    path('default_emails',default_email,name='default_emails'),

    path('update_email/<int:pk>',update_email,name='update_email'),

    path('delete_email/<int:pk>',delete_email,name='delete_email'),
]

visiting_card_portal/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("lead_manager/", include("lead_manager.urls")),
    path("email_manager/",include("email_manager.urls")),
    path("sms_manager/",include("sms_manager.urls")),
    path("send_sms/",include("send_sms.urls")),
    path("send_email/",include("send_email.urls")),
    path("default_sms/",include("default_sms.urls")),
    path("default_email/",include("default_email.urls")),
    path("client_sms/",include("client_sms.urls")),
    path("client_emails/",include("client_emails.urls")),
    path("client_accounts/",include("client_accounts.urls")),
    path("client_leads/",include("client_leads.urls")),
    
]

default_email/models.py
from django.db import models
# Create your models here.

class Default_Email(models.Model):
    subject = models.CharField(max_length=1000)
    to = models.CharField(max_length=1000,blank=True)
    greeting = models.CharField(max_length=1000,blank=True)
    message = models.TextField(max_length=2000)
    thank_you = models.CharField(max_length=1000,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.pk)

default_email/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy, reverse
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view

from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.template import loader
from django.utils.html import strip_tags

from default_email.models import Default_Email
from accounts.models import Portal_User
from lead_manager.models import Leads
from send_email.models import Email_Usage
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from default_email.serializer import Default_EmailSerializer

@api_view(['GET',])
def all_default_email(request):
    if request.method == "GET":
        all_emails = Default_Email.objects.all()
        serializer = Default_EmailSerializer(all_emails,many=True)
        return Response(serializer.data)  

@api_view(['POST',])
def send_bulk_email(request,pk):
    try:
        user = Portal_User.objects.get(pk=pk)
    except Portal_User.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method == "POST":
        data = {}
        email_pk = request.POST['email_pk']
        leads_list = request.POST.getlist('select_lead')
        email_object = Default_Email.objects.get(pk=email_pk)
        subject = email_object.subject
        message = email_object.message
        html_message = loader.render_to_string(
                'send_email/e_msg.html',
                {
                    'to':email_object.to,
                    'greeting':email_object.greeting,
                    'message': email_object.message,
                    'thank_you':email_object.thank_you
                }
            )
        for lead in leads_list:
            lead_object = Leads.objects.get(pk=lead)   
            email = lead_object.email_id
            
            text_content = strip_tags(html_message)
            # send_mail(subject,'finitytechserv@gmail.com',[email],fail_silently=True,html_message=html_message)
            send_mail(subject,message,'finitytechserv@gmail.com',[email],fail_silently=True,html_message=html_message)
            # mail.send()
            Email_Usage.objects.create(lead_name = lead_object.name,
                                       lead_email = email,
                                       send_from = user,
                                       status = "success",)
        data['response']="Email Send Successfully"
        return Response(data)   

@login_required(login_url = '/accounts/admin_login')
def default_email(request):
    all_emails = Default_Email.objects.all()
    if request.method == "POST":
        subject = request.POST['subject']
        to = request.POST['to']
        greeting = request.POST['greeting']
        message = request.POST['message']
        thank_you = request.POST['thank_you']
        Default_Email.objects.create(subject=subject,
                                   to=to,
                                    greeting=greeting,
                                    message=message,
                                    thank_you=thank_you)
        return HttpResponseRedirect(reverse('default_email:default_emails'))

    data = {'all_data':all_emails}
    return render(request,'default_email/default_emails.html',data)

def update_email(request,pk):
    email_object = Default_Email.objects.get(pk=pk)
    if request.method == "POST":
        subject = request.POST['subject']
        to = request.POST['to']
        greeting = request.POST['greeting']
        message = request.POST['message']
        thank_you = request.POST['thank_you']
        email_object.subject = subject
        email_object.to = to
        email_object.greeting = greeting
        email_object.message = message
        email_object.thank_you = thank_you
        email_object.save()
        return HttpResponseRedirect(reverse('default_email:default_emails'))

def delete_email(request,pk):
    email_object = Default_Email.objects.get(pk=pk)
    email_object.delete()
    return HttpResponseRedirect(reverse('default_email:default_emails'))

templates/default_email/default_emails.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block stylesheets %}

<!-- DataTables -->
<link href="{% static 'lead_manager/assets/plugins/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'lead_manager/assets/plugins/datatables/buttons.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
<!-- Responsive datatable examples -->
<link href="{% static 'lead_manager/assets/plugins/datatables/responsive.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />


{% endblock stylesheets %}

{% block headscript %}
{% endblock headscript %}

{% block content %}
<div class="modal fade" id="add_user" tabindex="-1" role="dialog" aria-labelledby="add_statusModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content rounded-0">
            <div class="modal-header">
                <h5 class="modal-title text-center" id="lead_satus_modal">
                    <font color="#000" size="5px;">Add Email</font>
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span>
                    </button>
                </h5>
            </div>
            <div class="modal-body" style="border-radius: 10px;">
                <form action="#" method="post">
                    {% csrf_token %}
                       <div class="form-group">
                            <label for="name">Subject</label>
                            <input id="name" type="text" class="form-control" name="subject" placeholder="Enter Subject" required>
                        </div>
                        
                        <div class="form-group">
                            <label for="name">To</label>
                            <input id="name" type="text" class="form-control" name="to" placeholder="Enter To" required>
                        </div>
                        <div class="form-group">
                            <label for="name">Greeting</label>
                            <input id="name" type="text" class="form-control" name="greeting" placeholder="Enter Greeting" required>
                        </div>

                        <div class="form-group">
                            <label for="message">Message </label>
                            <input id="message" type="text" class="form-control"  name="message" placeholder="Enter Message" required>
                        </div>
                        <div class="form-group">
                            <label for="name">Thank You</label>
                            <input id="name" type="text" class="form-control" name="thank_you" placeholder="Enter Thank You" required>
                        </div>
                    <center>
                            <button type="submit" class="btn-primary">Submit</button>
                        </center>
                </form>
            </div>

        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card m-b-30">
            <div class="card-body">
                <button type="submit" data-toggle="modal" data-target="#add_user" class="btn btn-info waves-effect waves-light" style="float: right">
                    Add Email
                </button>
                <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap text-center" style="border-collapse: collapse; border-spacing: 0; width: 100%;">

                    <thead>
                        <tr>
                            <th>Sr.No.</th>
                            <th>Subject</th>
                            <td>To</td>
                            <td>Greeting</td>
                            <th>Message</th>
                            <th>Thank You</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>


                    <tbody>
                    {% for email in  all_data %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{email.subject}}</td>
                            <td>{{email.to}}</td>
                            <td>{{email.greeting}}</td>
                            <td>{{email.message}}</td>
                            <td>{{email.thank_you}}</td>
                             <td><button type="button" class="update-sms btn btn-sm btn-primary" data-toggle="modal" data-target="#update_user{{email.pk}}">
                            <span class="fa fa-edit"></span></button>
                            <div class="modal fade" id="update_user{{email.pk}}" tabindex="-1" role="dialog" aria-labelledby="add_statusModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content rounded-0">
            <div class="modal-header">
                <h5 class="modal-title text-center" id="lead_satus_modal">
                    <font color="#000" size="5px;">Update Email</font>
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span>
                    </button>
                </h5>
            </div>
            <div class="modal-body" style="border-radius: 10px;">
                <form action="{% url 'default_email:update_email' email.pk %}" method="post">
                    {% csrf_token %}
                       <div class="form-group">
                            <label for="name">Subject</label>
                            <input id="name" type="text" class="form-control" name="subject" value="{{email.subject}}" required>
                        </div>
                        
                        <div class="form-group">
                            <label for="name">To</label>
                            <input id="name" type="text" class="form-control" name="to" value="{{email.to}}" required>
                        </div>
                        <div class="form-group">
                            <label for="name">Greeting</label>
                            <input id="name" type="text" class="form-control" name="greeting" value="{{email.greeting}}" required>
                        </div>

                        <div class="form-group">
                            <label for="message">Message </label>
                            <input id="message" type="text" class="form-control" max-length="150" name="message" value="{{email.message}}" required>
                        </div>
                        <div class="form-group">
                            <label for="name">Thank You</label>
                            <input id="name" type="text" class="form-control" name="thank_you" value="{{email.thank_you}}" required>
                        </div>
                    <center>
                            <button type="submit" class="btn-primary">Submit</button>
                        </center>
                </form>
            </div>

        </div>
    </div>
</div>
</td>
                            <td><button type="button" data-toggle="modal" data-target="#delete_user{{email.pk}}" class="delete-sms btn btn-sm btn-danger" >
                            <span class="fa fa-trash"></span></button>
                            <div class="modal fade" id="delete_user{{email.pk}}" tabindex="-1" role="dialog" aria-labelledby="add_statusModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-md" role="document">
                                <div class="modal-content rounded-0">
                                    <div class="modal-header">
                                        <h5 class="modal-title text-center" id="lead_satus_modal">
                                            <font color="#000" size="5px;">Delete Email</font>
                                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span>
                                            </button>
                                        </h5>
                                    </div>
                                    <div class="modal-body" style="border-radius: 10px;">
                                        <form action="{% url 'default_email:delete_email' email.pk %}" method="post">
                                            {% csrf_token %}
                                            <center>
                                                Are you sure you want to delete Email ?
                                            </center>
                                            <br>
                                            <center>
                                                <button type="submit" class="btn-danger">Delete</button>
                                            </center>
                                        </form>
                                    </div>

                                </div>
                            </div>
                        </div>


</td>
                        </tr>
                        {% endfor %}
                        {% comment %} <tr>
                            <td>2</td>
                            <td>Hello</td>
                            <td>Dear Sir</td>
                            <td>Good Morning</td>
                            <td>Visit www.finitytechserv.com</td>
                            <td>Thank You</td>
                            <td>Edit</td>
                            <td>Delete</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>Hello</td>
                            <td>Dear Sir</td>
                            <td>Good Morning</td>
                            <td>Visit www.finitytechserv.com</td>
                            <td>Thank You</td>
                            <td>Edit</td>
                            <td>Delete</td>
                        </tr> {% endcomment %}
                    </tbody>
                </table>

            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->

{% endblock %}

{% block script %}
<!-- Required datatable js -->
<script src="{% static 'lead_manager/assets/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'lead_manager/assets/plugins/datatables/dataTables.bootstrap4.min.js' %}"></script>

<!-- Buttons examples -->
<script src="{% static 'lead_manager/assets/plugins/datatables/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'lead_manager/assets/plugins/datatables/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'lead_manager/assets/plugins/datatables/jszip.min.js' %}"></script>
<script src="{% static 'lead_manager/assets/plugins/datatables/pdfmake.min.js' %}"></script>
<script src="{% static 'lead_manager/assets/plugins/datatables/vfs_fonts.js' %}"></script>
<script src="{% static 'lead_manager/assets/plugins/datatables/buttons.html5.min.js' %}"></script>
<script src="{% static 'lead_manager/assets/plugins/datatables/buttons.print.min.js' %}"></script>
<script src="{% static 'lead_manager/assets/plugins/datatables/buttons.colVis.min.js' %}"></script>
<!-- Responsive examples -->
<script src="{% static 'lead_manager/assets/plugins/datatables/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'lead_manager/assets/plugins/datatables/responsive.bootstrap4.min.js' %}"></script>

<!-- Datatable init js -->
<script src="{% static 'lead_manager/assets/pages/datatables.init.js' %}"></script>
{% endblock %}

{% block extrascript %}
{% endblock extrascript %}